vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /img/properties
            upload_destination: '%kernel.project_dir%/public/img/properties'
            namer:
                service: vich_uploader.namer_property
                options: { property: 'pseudo' }

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
